import sqlite3

pragma_list = ['auto_vacuum',
'automatic_index',
'busy_timeout',
'cache_size',
'case_sensitive_like',
'checkpoint_fullfsync',
'collation_list',
'compile_options',
'count_changes',
'data_store_directory',
'database_list',
'default_cache_size',
'empty_result_callbacks',
'encoding',
'foreign_key_list',
'foreign_keys',
'freelist_count',
'full_column_names',
'fullfsync',
'ignore_check_constraints',
'incremental_vacuum',
'index_info',
'index_list',
'integrity_check',
'journal_mode',
'journal_size_limit',
'legacy_file_format',
'locking_mode',
'max_page_count',
'page_count',
'page_size',
'parser_trace',
'quick_check',
'read_uncommitted',
'recursive_triggers',
'reverse_unordered_selects',
'schema_version',
'secure_delete',
'short_column_names',
'shrink_memory',
'synchronous',
'table_info',
'temp_store',
'temp_store_directory',
'user_version',
'vdbe_listing',
'vdbe_trace',
'wal_autocheckpoint',
'wal_checkpoint',
'writable_schema']

con = sqlite3.connect(":memory:")

for p in pragma_list :
  print p, ':', con.execute("PRAGMA %s" % (p,)).fetchone()